'use strict';

const PROGRAMS = [
  { id: 'sepm', name: 'School of Excellence in Product Management', provider: 'SEPM / 360 Lead Solutions', partnership: 'PSDF', region: 'Pakistan', duration: '12 weeks', format: 'Online + In-Person', lang: ['English', 'Urdu'], url: 'http://sepm.alibinnadeem.com', notion_url: 'https://alibinnadeem.notion.site/School-of-Excellence-in-Product-Management-SEPM-5c91ee379d8848cea58ad4dde64bb345', open: true },
  { id: 'asm', name: 'Agile Scrum Master Certification', provider: '360 Lead Solutions', partnership: 'PSDF', region: 'Pakistan', duration: '4 weeks', format: 'Online', lang: ['English', 'Urdu'], url: 'http://360marketingzone.com', open: true },
  { id: 'tech-mgr', name: 'Technology for Managers', provider: '360 Lead Solutions', partnership: 'PSDF', region: 'Pakistan', duration: '6 weeks', format: 'Online', lang: ['English'], url: 'http://360marketingzone.com', open: true },
  { id: 'dta', name: 'Digital Transformation Awareness', provider: '360 Lead Solutions', partnership: 'PSDF', region: 'Pakistan', duration: '2 days', format: 'Workshop', lang: ['English', 'Urdu'], url: 'http://360marketingzone.com', open: true },
  { id: 'qccd-pm', name: 'Product Management Certificate (Gulf)', provider: 'QCCD / 360 Lead Solutions', partnership: 'QCCD', region: 'Qatar/GCC', duration: '8 weeks', format: 'Online + Workshop', lang: ['English', 'Arabic'], url: 'http://qccd.net', open: true },
  { id: 'qccd-lead', name: 'Global Leadership Development (Gulf)', provider: 'QCCD / 360 Lead Solutions', partnership: 'QCCD', region: 'Qatar/GCC', duration: '6 weeks', format: 'Online', lang: ['English'], url: 'http://qccd.net', open: true },
];

const SERVICES = [
  {
    id: 'digital-transformation',
    name: 'Digital Transformation',
    icon: '⚙️',
    tagline: 'End-to-end enterprise modernisation',
    tags: ['Strategy', 'ERP/CRM', 'Automation', 'Change Mgmt'],
    engagement_types: ['advisory-sprint', 'full-build'],
    reference_links: { 'ARD City': 'https://theardcity.com', 'Grand City': 'https://grandcity.pk' },
    outcomes: { domains_transformed: 17, tasks_delivered: 431, platforms_live: 9 },
  },
  {
    id: 'ai-strategy',
    name: 'AI Strategy & Product',
    icon: '🧠',
    tagline: 'From roadmap to production ML - end to end',
    tags: ['AI Roadmap', 'ML Pipelines', 'Product Strategy', 'Predictive Analytics'],
    engagement_types: ['advisory-sprint', 'fractional-cto', 'full-build'],
    outcomes: { downtime_reduction: '32%', platform_value: '$200M+' },
  },
  {
    id: 'fractional-cto',
    name: 'Fractional CTO',
    icon: '🎯',
    tagline: 'CTO-level leadership embedded in your team',
    tags: ['Tech Leadership', 'Team Building', 'Architecture', 'Fundraising Support'],
    engagement_types: ['fractional-cto'],
    outcomes: { ventures_operated: 21, live_systems: 23, years_experience: '15+' },
  },
  {
    id: 'real-estate-tech',
    name: 'Real Estate Tech & PropTech',
    icon: '🏙️',
    tagline: 'Smart city · Developer CRM · RWA tokenization',
    tags: ['Smart City ERP', 'PropTech', 'Blockchain RWA', 'CRM/CX'],
    engagement_types: ['advisory-sprint', 'full-build'],
    reference_links: { 'Syntiant Atlas': 'https://syntiantatlas-web.vercel.app', 'Grand City': 'https://grandcity.pk', 'ARD City': 'https://theardcity.com' },
  },
  {
    id: 'defence-advisory',
    name: 'Defence Technology Advisory',
    icon: '🚁',
    tagline: 'UAV systems · Counter-drone · Tactical tech strategy',
    tags: ['UAV Systems', 'C-UAS', 'Defence Procurement', 'Tech Strategy'],
    engagement_types: ['advisory-sprint'],
    standards: ['NATO STANAG 4671', 'ISO 2408', 'ASTM A500-B', 'ETAG 027', 'ICAO Perimeter'],
    reference_links: { 'Canis Technology': 'https://canistechsol.vercel.app', 'ADS Configurator': 'https://alibinnadeem-ai.github.io/ADS-Buyer_portal/' },
  },
  {
    id: 'healthcare-it',
    name: 'Healthcare IT Consulting',
    icon: '🏥',
    tagline: 'RCM · Medical billing · Clinical AI',
    tags: ['RCM Setup', 'Billing Ops', 'Clinical AI', 'Compliance'],
    engagement_types: ['advisory-sprint', 'full-build'],
    outcomes: { us_clients: '35+', claims_cost_reduction: '40%' },
    reference_links: { 'My Health Aiyin': 'https://myhealthaiyin.framer.ai' },
  },
  {
    id: 'training',
    name: 'Training & Capacity Building',
    icon: '🎓',
    tagline: 'SEPM · Agile · PSDF · QCCD Qatar',
    tags: ['SEPM', 'Agile/ASM', 'PSDF', 'QCCD Qatar'],
    engagement_types: ['training'],
    programs: [
      { id: 'sepm', name: 'School of Excellence in PM', duration: '12 weeks', url: 'http://sepm.alibinnadeem.com' },
      { id: 'asm', name: 'Agile Scrum Master', duration: '4 weeks', url: 'http://360marketingzone.com' },
      { id: 'tech-mgr', name: 'Technology for Managers', duration: '6 weeks', url: 'http://360marketingzone.com' },
      { id: 'dta', name: 'Digital Transformation Awareness', duration: '2 days', url: 'http://360marketingzone.com' },
    ],
  },
  {
    id: 'offshore-teams',
    name: 'Offshore Tech Teams (CETEM)',
    icon: '🔬',
    tagline: 'Senior Pakistan-based talent for US & international clients',
    tags: ['Resource Aug', 'Offshore Mgmt', 'Pakistan Tech Talent', 'Agile Delivery'],
    engagement_types: ['full-build', 'fractional-cto'],
    roles: ['Full-stack (React, Next.js, Node, NestJS)', 'Backend (Python, Java, .NET)', 'DevOps (AWS, Azure, GCP)', 'Product Managers', 'QA & Data Scientists'],
    reference_links: { CETEM: 'http://cetem.canisrufus.org/', 'CETEM Resume': 'https://resume.cetem.canisrufus.org/' },
  },
  {
    id: 'investment',
    name: 'Investment & Qantara Commercials',
    icon: '🪙',
    tagline: 'Syntiant Atlas RWA · ARD City Overseas Corporate Relations',
    tags: ['RWA Tokenization', 'Fractional RE', 'Qantara', 'RUDA Phase 1'],
    engagement_types: ['advisory-sprint'],
    outcomes: { min_investment: 'PKR 50,000', model: 'RWA Tokenization', location: 'RUDA Phase 1' },
    reference_links: { 'Syntiant Atlas': 'https://syntiantatlas-web.vercel.app', 'ARD City': 'https://theardcity.com' },
  },
];

const PROJECTS = [
  { id: 'ardcrm', cat: 'CRM & Sales', name: 'ARD CRM', url: 'https://ardcrm.vercel.app', stack: ['Next.js', 'PostgreSQL', 'Prisma'], status: 'live' },
  { id: 'contractorcrm', cat: 'CRM & Sales', name: 'Contractor CRM', url: 'https://contractorcrm.vercel.app', stack: ['React', 'SQLite', 'Express'], status: 'live' },
  { id: 'geartrybe-crm', cat: 'CRM & Sales', name: 'Gear Trybe CRM', url: 'https://geartrybe-crm.netlify.app', stack: ['React', 'Node.js'], status: 'live' },
  { id: 'ard-sales', cat: 'CRM & Sales', name: 'ARD Sales Intelligence', url: 'https://ard-master-sales.vercel.app', stack: ['Next.js', 'NestJS'], status: 'live' },
  { id: 'pso-os', cat: 'Admin & Ops', name: 'PSO OS - Executive Command', url: 'https://pso-os.vercel.app', stack: ['Next.js 14', 'Prisma', 'NextAuth'], status: 'live' },
  { id: 'ard-command', cat: 'Admin & Ops', name: 'ARD Executive Command Center', url: 'https://ard-command-center.vercel.app', stack: ['Next.js', 'PostgreSQL'], status: 'live' },
  { id: 'ruda-eos', cat: 'Admin & Ops', name: 'RUDA Execution OS', url: 'https://ruda-eos.vercel.app', stack: ['React', 'Express'], status: 'live' },
  { id: 'boardsync', cat: 'Admin & Ops', name: 'BoardSync', url: 'https://boardsyncs.vercel.app', stack: ['Vanilla JS', 'Node.js'], status: 'live' },
  { id: 'ard-ams', cat: 'Admin & Ops', name: 'ARD Asset Management System', url: 'https://ard-ams.vercel.app', stack: ['React', 'PostgreSQL'], status: 'live' },
  { id: 'gcaseflow', cat: 'Admin & Ops', name: 'Grand Case Flow', url: 'https://grandcaseflow.vercel.app', stack: ['Next.js', 'Neon'], status: 'live' },
  { id: 'activityhub', cat: 'Admin & Ops', name: 'ActivityHub Pro', url: 'https://activityhub.vercel.app/', stack: ['React', 'Node.js'], status: 'live' },
  { id: 'advance-pm', cat: 'AI Platform', name: 'Advance AI Project Management', url: 'https://advance-pm.vercel.app', stack: ['React', 'AI'], status: 'live' },
  { id: 'ard-admin', cat: 'Real Estate', name: 'ARD City Admin Dashboard', url: 'https://ardcityadmindashboard.vercel.app', stack: ['React', 'Vite'], status: 'live' },
  { id: 'grand-admin', cat: 'Real Estate', name: 'Grand City Admin Dashboard', url: 'https://grandcityadmindashboard.vercel.app', stack: ['React', 'Vite'], status: 'live' },
  { id: 'ard-utility', cat: 'Real Estate', name: 'ARD Utility Bills', url: 'https://ardutilitybills.vercel.app', stack: ['React', 'Chart.js'], status: 'live' },
  { id: 'gck-dashboard', cat: 'Real Estate', name: 'GCK Dashboard', url: 'https://gck-dashboard-nine.vercel.app', stack: ['Next.js'], status: 'live' },
  { id: 'syntiant', cat: 'PropTech', name: 'Syntiant Atlas', url: 'https://syntiantatlas-web.vercel.app', stack: ['Next.js', 'Blockchain'], status: 'live' },
  { id: 'myhealth-platform', cat: 'Healthcare', name: 'My Health Aiyin Platform', url: 'https://myhealthaiyin.framer.ai', stack: ['Framer', 'AI'], status: 'live' },
  { id: 'canis-site', cat: 'Defence', name: 'Canis Technology Solutions', url: 'https://canistechsol.vercel.app', stack: ['Next.js', 'React'], status: 'live' },
  { id: 'ads', cat: 'Defence', name: 'Anti-Drone System Configurator', url: 'https://alibinnadeem-ai.github.io/ADS-Buyer_portal/', stack: ['Three.js', 'Vanilla JS'], status: 'live' },
  { id: 'tactical-deck', cat: 'Defence', name: 'Tactical Excellence Deck', url: 'https://tactical-excellence-in-m-z1g0vwm.gamma.site', stack: ['Gamma'], status: 'live', note: 'Canis investor deck - $73B->$163B, 14.3% CAGR' },
  { id: 'mattress-site', cat: 'Retail', name: 'Bin Nadeem Mattress House', url: 'https://binnadeemmattresses.vercel.app', stack: ['Next.js', 'React'], status: 'live' },
  { id: 'national-tv', cat: 'Media', name: 'National TV Interview', url: 'https://www.youtube.com/watch?v=FCCeDuNruUE', stack: ['YouTube'], status: 'live', note: 'Entrepreneurship, AI, and tech leadership on national TV' },
];

const VENTURES = [
  { id: 'aiyin', name: 'Aiyin Inc.', type: 'Enterprise Technology', role: 'Founder & CEO', url: 'https://aiyin.us', founded: 2017, status: 'active' },
  { id: 'myhealth', name: 'My Health Aiyin', type: 'Healthcare IT / RCM', role: 'Co-Founder & CEO', url: 'https://myhealthaiyin.framer.ai', founded: 2019, status: 'active' },
  { id: 'caremyhealth', name: 'Care My Health Aiyin', type: 'Healthcare BPO', role: 'Founder', url: 'https://care.myhealth.aiyin.us/', founded: 2021, status: 'active' },
  { id: 'geartrybe', name: 'Gear Trybe', type: 'US Automotive', role: 'Founder', url: 'http://geartrybe.aiyin.us/', founded: 2022, status: 'active', phone: '+1 (408) 500 1113' },
  { id: 'canis', name: 'Canis Technology Solutions', type: 'Defence Technology', role: 'Co-Founder & Product Manager', url: 'https://canistechsol.vercel.app', founded: 2009, status: 'active' },
  { id: 'tectrybe', name: 'Tectrybe Inc.', type: 'AI Software', role: 'Founder & CEO', url: 'http://tectrybe.com', founded: 2020, status: 'active' },
  { id: 'altertec', name: 'Altertec.ai', type: 'AI Platform', role: 'Co-Founder', url: 'http://altertec.ai', founded: 2023, status: 'active' },
  { id: 'cyberx', name: 'CyberX Consulting', type: 'Technology Consulting', role: 'CTO', url: 'https://cyberxconsulting.com/', founded: 2020, status: 'active' },
  { id: 'ksa', name: 'KSA International Corporation', type: 'Medical Equipment', role: 'Chief Technology Consultant', url: 'https://ksainternationalcorporation.com/', founded: 2015, status: 'active', products: 367, countries: 100 },
  { id: 'axon', name: 'Axon Global', type: 'Workforce Mobility', role: 'Co-Founder', url: 'https://axon-global-74v0q6a.gamma.site/', founded: 2023, status: 'active' },
  { id: '360lead', name: '360 Lead Solutions Pvt. Ltd.', type: 'Training & Education', role: 'Owner', url: 'http://360marketingzone.com', founded: 2021, status: 'active' },
  { id: 'sepm', name: 'School of Excellence in Product Management', type: 'Education', role: 'Founder & Director', url: 'http://sepm.alibinnadeem.com', founded: 2021, status: 'active' },
  { id: 'see', name: 'SEE - School of Excellence for Entrepreneurs', type: 'Education', role: 'Founder', url: 'https://see-entrepreneurs-2kq6dwo.gamma.site/', founded: 2022, status: 'active' },
  { id: 'cetem', name: 'CETEM', type: 'Resource Augmentation', role: 'Director', url: 'http://cetem.canisrufus.org/', founded: 2018, status: 'active' },
  { id: 'bna', name: 'Bin Nadeem Associates', type: 'Consultancy', role: 'Assistant Manager -> Consultant', url: 'https://binnadeem.com/bnaconsultants/', founded: 2014, status: 'active' },
  { id: 'syntiant', name: 'Syntiant Atlas', type: 'PropTech / Blockchain', role: 'CEO & Founder', url: 'https://syntiantatlas-web.vercel.app', founded: 2024, status: 'active', min_investment: 'PKR 50,000' },
  { id: 'mattress', name: 'Bin Nadeem Mattress House', type: 'Retail', role: 'Owner', url: 'https://binnadeemmattresses.vercel.app', founded: 2019, status: 'active' },
  { id: 'upvc', name: 'UPVC Windows Factory', type: 'Manufacturing', role: 'Owner', url: 'https://binnadeem.com/upvc/', founded: 2017, status: 'active' },
  { id: 'ledgerly', name: 'Ledgerly Tax Pros', type: 'US Finance / Tax', role: 'Founder', url: 'https://ledgerlytaxpros.com/', founded: 2023, status: 'active' },
  { id: 'smilefactory', name: 'The Smile Factory DBS', type: 'Dental Billing / RCM', role: 'Founder', url: 'http://thesmilefactorydbs.com/', founded: 2023, status: 'active' },
  { id: 'medbilling', name: 'MedBilling Unified Solutions of America', type: 'US Medical Billing', role: 'Founder', url: 'https://musamyhealth.com/', founded: 2022, status: 'active' },
];

const EVENT_TYPES = {
  'fractional-cto': 'fractional-cto-discovery',
  'advisory-sprint': 'advisory-sprint',
  'digital-transformation': 'digital-transformation',
  'ai-strategy': 'ai-strategy-call',
  'defence-advisory': 'defence-tech-advisory',
  'healthcare-it': 'healthcare-it',
  training: 'training-programs',
  'offshore-teams': 'offshore-teams',
  investment: 'investment-intro',
  default: 'discovery-call',
};

module.exports = {
  PROGRAMS,
  SERVICES,
  PROJECTS,
  VENTURES,
  EVENT_TYPES,
};
